In [1]:
# h = ReLu(Wx+b) implementation
# here x = input
# W = weight
# b = bias


# import tensorlfow
import os
import tensorflow as tf
import numpy as np
tf.reset_default_graph()


In [2]:
# create the input placeholder
x = tf.placeholder(tf.float32, shape=[None, 784], name='X')

In [3]:
# create weight matrix initialized randomely from N(0, 0.01)
weight_initer = tf.truncated_normal_initializer(mean=0.0, stddev=0.01)
W = tf.get_variable(name="Weight", dtype=tf.float32, shape=[784, 200], initializer=weight_initer)

# create bias vector of size 200, all initialized as zero
bias_initer =tf.constant(0., shape=[200], dtype=tf.float32)
b = tf.get_variable(name="Bias", dtype=tf.float32, initializer=bias_initer)

In [4]:
# create matmul node
x_w = tf.matmul(x, W, name='MatMul')
#create add node
x_w_b = tf.add(x_w, b, name='Adding')
#create ReLu node
h = tf.nn.relu(x_w_b, name='ReLu')

# Add an Op to initialize variables
init_op = tf.global_variables_initializer()

## tensorboard coding start

# A scalar summary for the scalar tensor
scalar_summary = tf.summary.scalar('My_scalar_summary', x)
# A histogram summary for the non-scalar (i.e. 2D or matrix) tensor
histogram_summary = tf.summary.histogram('My_histogram_summary', x_w_b)

# ____step 2:____ merge all summaries
merged = tf.summary.merge_all()
## tensorboard coding end here
# launch the graph in a session
with tf.Session() as sess:
    # initialize variables
    sess.run(init_op)
    # create the dictionary:
    d = {x: np.random.rand(100, 784)}
    # feed it to placeholder a via the dict 
    print(sess.run(h, feed_dict=d))
    
    #saving for tensorboard
    # to visualize run : tensorboard --logdir=graphs --port=6006
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    
    #for saving the model
    saver = tf.train.Saver()
    saved_path = saver.save(sess, 'train/'+'./saved_variable')
    print('model saved in {}'.format(saved_path))
    
    ## Restore the model
    # restore the saved vairable
    saver.restore(sess, 'train/'+'./saved_variable')
    # print the loaded variable
    W_out, b_out = sess.run([W, b])
    print('W = ', W_out)
    print('b = ', b_out)
    
    # import the graph from the file
    imported_graph = tf.train.import_meta_graph('train/saved_variable.meta')

    # list all the tensors in the graph
    for tensor in tf.get_default_graph().get_operations():
        print (tensor.name)
    
# if the there is no file saved just use try catch to avoid error
"""
try:
   with tf.Session() as sess:
    # initialize variables
    sess.run(init_op)
    # create the dictionary:
    d = {x: np.random.rand(100, 784)}
    # feed it to placeholder a via the dict 
    print(sess.run(h, feed_dict=d))
    
    #saving for tensorboard
    # to visualize run : tensorboard --logdir=graphs --port=6006
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    
    #for saving the model
    saver = tf.train.Saver()
    saved_path = saver.save(sess, 'train/'+'./saved_variable')
    print('model saved in {}'.format(saved_path))
    
    ## Restore the model
    # restore the saved vairable
    saver.restore(sess, 'train/'+'./saved_variable')
    # print the loaded variable
    W_out, b_out = sess.run([W, b])
    print('W = ', W_out)
    print('b = ', b_out)


except Exception as e:
    print(str(e))
 
"""
 

[[0.         0.16834995 0.         ... 0.         0.         0.04257778]
 [0.         0.28792515 0.         ... 0.         0.         0.04369999]
 [0.         0.16395102 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.17434464 0.         ... 0.08938134 0.         0.        ]
 [0.         0.06386861 0.         ... 0.12678799 0.         0.        ]
 [0.         0.10893186 0.         ... 0.         0.         0.12867385]]
model saved in train/./saved_variable
INFO:tensorflow:Restoring parameters from train/./saved_variable
W =  [[-0.01347397 -0.00856969  0.00054788 ...  0.00350333 -0.00871212
   0.00775196]
 [-0.00896794 -0.01363653  0.00126106 ... -0.01578897  0.00854675
   0.01188983]
 [-0.01715375 -0.00688049 -0.01775046 ...  0.00281724 -0.0011602
   0.00954298]
 ...
 [-0.00323366  0.0035921   0.01733937 ... -0.01869217  0.00266128
   0.00188603]
 [-0.0124047   0.00647159 -0.01497028 ... -0.00741428  0.0037337
  -0.00753683]
 [-0.00536639 -0.0109773   0.00148979 ..

"\ntry:\n   with tf.Session() as sess:\n    # initialize variables\n    sess.run(init_op)\n    # create the dictionary:\n    d = {x: np.random.rand(100, 784)}\n    # feed it to placeholder a via the dict \n    print(sess.run(h, feed_dict=d))\n    \n    #saving for tensorboard\n    # to visualize run : tensorboard --logdir=graphs --port=6006\n    writer = tf.summary.FileWriter('./graphs', sess.graph)\n    \n    #for saving the model\n    saver = tf.train.Saver()\n    saved_path = saver.save(sess, 'train/'+'./saved_variable')\n    print('model saved in {}'.format(saved_path))\n    \n    ## Restore the model\n    # restore the saved vairable\n    saver.restore(sess, 'train/'+'./saved_variable')\n    # print the loaded variable\n    W_out, b_out = sess.run([W, b])\n    print('W = ', W_out)\n    print('b = ', b_out)\n\n\nexcept Exception as e:\n    print(str(e))\n \n"

In [5]:
# check the saved file
for file in os.listdir('train'):
    if 'saved_variable' in file:
        print(file)

saved_variable1.meta
saved_variable1.data-00000-of-00001
saved_variable.meta
saved_variable.index
saved_variable1.index
saved_variable.data-00000-of-00001
